Adding a "status" command to the tt-web-app-init script
This will return an error status if either httpd or tomcat (e.g. tt-oib) is in
an error state, and is necessary for ZDD deployments

Change-Id: I6c5665ceee47be599249748e77ea39c08ab538a0

diff --git a/config/system/tt-web-app-init b/config/system/tt-web-app-init
--- a/config/system/tt-web-app-init
+++ b/config/system/tt-web-app-init
@@ -4,10 +4,10 @@
 #
 # tt-web-app
 #
-# init script for all componenents of a Beacon web server
+# init script for all components of a Beacon web server
 #       
 # chkconfig: 2345 90 15
-# description: init script for all componenents of a Beacon server
+# description: init script for all components of a Beacon server
 #
 #-------------------------------------------------------------------------
 
@@ -24,7 +24,7 @@ SLEEP_SECONDS=5
 TOMCAT_SUCCESS_STRING="Server startup in"
 
 #
-# Determine Apache INITD filename programattically from this file name 
+# Determine Apache INITD filename programatically from this file name
 # by trimming the trailing "-web-app"
 # e.g. if this file is tt-web-app, then /etc/init.d/tt
 # e.g. if this file is tt-webassess-web-app, then /etc/init.d/tt-webassess
@@ -35,15 +35,15 @@ THREETWELVE_INITD=/etc/init.d/${NAME%"-web-app"}
 source /etc/init.d/functions
 
 function err_msg(){
-echo 
-echo "===================================================================="
-echo "[ERROR] error starting ${PROGRAM}"
-echo 
-echo $1
-echo 
-echo "===================================================================="
-echo
-echo_failure
+    echo
+    echo "===================================================================="
+    echo "[ERROR] error starting ${PROGRAM}"
+    echo
+    echo $1
+    echo
+    echo "===================================================================="
+    echo
+    echo_failure
 }
 
 start() {
@@ -143,6 +143,28 @@ stop() {
     echo
 }
 
+status() {
+    $THREETWELVE_INITD status
+    tomcat_ret_val=$?
+
+    if [ $tomcat_ret_val -ne 0 ]
+    then
+        echo "tomcat returned an error status"
+        return $tomcat_ret_val
+    fi
+
+    $HTTPD_INITD status
+    apache_ret_val=$?
+
+    if [ $apache_ret_val -ne 0 ]
+    then
+        echo "httpd returned an error status"
+        return $apache_ret_val
+    fi
+
+    return 0;
+}
+
 # main entry point
 case "$1" in
   start)
@@ -151,8 +173,11 @@ case "$1" in
   stop)
 	stop
 	;;
+  status)
+    status
+    ;;
   *)
-	echo $"Usage: $prog {start|stop}"
+	echo $"Usage: $prog {start|stop|status}"
 	exit 1
 esac
 
